micronaut:
  application:
    name: pixRest
  server:
    port: 'localhost:8080'

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    pixRest:
      address: 'localhost:50052'
      plaintext: true
      max-retry-attempts: 5