micronaut:
  application:
    name: pixRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    pix:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 5